/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.AEINK2007;

import java.util.Scanner;
public class App {
    public String getGreeting() {
        return "Hola AEINK";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Programacion estructurada");
        tabla_multiplicar();
        
    }
    public static void tabla_multiplicar(){
        System.out.println("Tabla de multiplicar de un numero");
        System.out.println("INgrese un numero para mostrar su tabla");
        Scanner sc = new Scanner(System.in);
        
        int numero = sc.nextInt();
        
        for (int i = 1; i <= 12; i++) {
            int multi = i*numero;
            
            System.out.println("La multiplicacion de "+ i +" por "+ numero + " es igual a "+multi);
            
     
            
        }
        
        
    }
}
