/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.AEINK2007;

public class App {
    public String getGreeting() {
        return "Hola AEINK";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
